# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

# Use a package of configuration called an orb, see https://circleci.com/docs/2.0/orb-intro/
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.3.1

jobs:
    deploy_production:
      docker:
        - image: cibuilds/hugo:0.42.1
      working_directory: ~/project
      steps:
        - add_ssh_keys
        - checkout
        - run: |
            echo 'ngoisaonho.net ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBAulOk75DivZ670OFX7MoJGYAHpbQwdX3bggBndGNfsVpR+cZLlVov/EvaUH/7gJmC4nPHykXhohgdBhcKB3Mxs=' >> ~/.ssh/known_hosts
            ssh nginx@ngoisaonho.net < ~/project/deployment/remote-deployment-staging.sh
            ssh root@ngoisaonho.net < ~/project/deployment/remote-create-nginx-config.sh
    deploy_staging:
      docker:
        - image: cibuilds/hugo:0.42.1
      working_directory: ~/project
      steps:
        - add_ssh_keys
        - checkout
        - run: |
            echo 'ngoisaonho.net ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBAulOk75DivZ670OFX7MoJGYAHpbQwdX3bggBndGNfsVpR+cZLlVov/EvaUH/7gJmC4nPHykXhohgdBhcKB3Mxs=' >> ~/.ssh/known_hosts
            ssh nginx@ngoisaonho.net < ~/project/deployment/remote-deployment-staging.sh
            ssh root@ngoisaonho.net < ~/project/deployment/remote-create-nginx-config.sh
# Orchestrate or schedule a set of jobs, see https://circleci.com/docs/2.0/workflows/
workflows:
  deploy_flow:
    jobs:
      - deploy_production:
          filters:
            branches:
              only: master
      - deploy_staging:
          filters:
            branches:
              only: staging
